
# This is a section

This is some text.

## This is a subsection

This is more text.

## This is another subsection

This is more text.

# Emphasis and Strong

Single asterisks `*` are for emphasis.

*This is emphasized.*

Double asterisks `**` are for strong.

**This is strong.**

# Lists

## Unordered Lists

List items start with `- `.

- item 1
- item 2
- item 3

# Preformatted and Code

## Code

this is `code`.

## Preformatted

```
this is
preformatted
```

# Blockquote

> this is a blockquote.

